### ISSUE TITLE
Version 0.30.0 of rusqlite supports creating loadable extension

### ISSUE THREAD

**Issue by gwenn** [asg017/sqlite-loadable-rs#17]
Hello,
Would you mind if we update the following sentence in your [README](https://github.com/asg017/sqlite-loadable-rs/blob/7e9a4a8417d9a161c928c0a61dec42f0296ea732/README.md?plain=1#L26):
> For Rust, [rusqlite](https://github.com/rusqlite/rusqlite) has had a few different PRs that attempted to add loadable extension support in that library, but none have been merged.

Since version [0.30.0](https://github.com/rusqlite/rusqlite/pull/1362), you should be able to create loadable extension with `rusqlite`.
Regards.

**Comment by asg017** [comment]
done, thanks for the note!
