### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tantaman** [asg017/sqlite-loadable-rs#7]
[According to the docs](https://docs.rs/rustc-std-workspace-std/1.0.1/std/ffi/struct.CString.html#method.into_raw), calling `into_raw` must be followed by a corresponding `from_raw` to deallocate the string.

Here you `into_raw`:

https://github.com/asg017/sqlite-loadable-rs/blob/784a4b33378e8b69819bd22fdfdcb7bfd24f0d08/src/api.rs#L290

but never have a corresponding `from_raw`

**Comment by asg017** [comment]
Thanks for reporting! Fixed in e461baf3f579986d2ea6cda43fd327db64ab7264 , aiming to make a release soon
